### ISSUE TITLE
outlet device not recognized

### ISSUE THREAD

**Issue by 27andrea** [madchicken/comelit-client#12]
outlet devices (others) are not recognized by comelit-client

**Comment by 27andrea** [comment]
Ciao,
Sei riuscito a verificare?
Il mio dispositivo altro (Outlet)
Non viene riconosciuto e non viene rilevato 
Si tratta di un tempo rizzato a 0 secondi che apre un carraio
Grazie mille
Andrea

**Comment by madchicken** [comment]
Ciao, sto rilasciando una versione che dovrebbe logore i dispositivi non riconosciuti, in modo da capire come mapparli in HomeKit

**Comment by 27andrea** [comment]
ciao,
ho provato ad aggiornare la versione ho lanciato il comando comelit outlets --list ma non trova nessun dispositivo
come posso recuperare tali dispositivi?
grazie

**Comment by madchicken** [comment]
Ciao, potresti provare con il client ad eseguire `comelit others --list` e vedere se funziona. Magari prova anche ad aprire e chiudere usando `toggle`

**Comment by 27andrea** [comment]
ho provato a lanciare il comando ma anche se lancio lo stesso comando con una light mi va in errore:

comelit lights --toggle 0



Sending message to HUB {"req_type":0,"seq_id":3,"req_sub_type":-1,"sessiontoken":"1600700437","obj_id":"0","detail_level":1}
Message queue size is 1
Rejecting unresolved promise after 9573ms ({"req_type":0,"seq_id":3,"req_sub_type":-1,"sessiontoken":"1600700437","obj_id":"0","detail_level":1})
Error while sending packet
Error: Timeout for message:  {"req_type":0,"seq_id":3,"req_sub_type":-1,"sessiontoken":"1600700437","obj_id":"0","detail_level":1}
    at C:\Users\andrea\AppData\Roaming\npm\node_modules\comelit-client\dist\promise-queue.js:29:38
    at Array.reduce (<anonymous>)
    at ComelitClient.cleanPending (C:\Users\andrea\AppData\Roaming\npm\node_modules\comelit-client\dist\promise-queue.js:25:44)
    at Timeout._onTimeout (C:\Users\andrea\AppData\Roaming\npm\node_modules\comelit-client\dist\promise-queue.js:19:22)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7)
Comelit client disconnected
Exiting

**Comment by 27andrea** [comment]
comelit others --list


Message processed. Message queue size is now 0
Resolving response 3
DOM#LD#21.6 - Carraio (status OFF)
Shutting down


lanciando toggle 0
a volte ricevo il timeout e a volte ricevo questo:
Message processed. Message queue size is now 0
Resolving response 3
Selected device does not exists

**Comment by madchicken** [comment]
puoi provare con questo comando per vedere se funziona il cancello?

    come lit others --toggle DOM#LD#21.6

**Comment by 27andrea** [comment]
Ciao, si avevo già provato ma mi dava device does not exist

**Comment by 27andrea** [comment]
per la precisione:



`Searching for Comelit HUB on LAN...
Server listening 0.0.0.0:59404
Found Comelit HUB at 192.168.1.49 (MAC 002529170311, Name Comelit Hub 1                       )
Connecting to Comelit HUB at mqtt://192.168.1.49 with clientID HSrv_C4105061-57D7-417A-AC52-543C454C5494 (user: hsrv-user, pwd sf1nE9bjPc)
Retrieving agent id...
Sending message to HUB {"req_type":13,"seq_id":1,"req_sub_type":-1,"agent_type":0}
Message queue size is 1
Received message with id 1
Resolving promise 1: {
  req_type: 13,
  req_sub_type: -1,
  seq_id: 1,
  req_result: 0,
  agent_type: 0,
  out_data: [ { agent_id: 4, descrizione: 'Comelit Hub 1' } ],
  status: NaN
}
Message processed. Message queue size is now 0
Logged into Comelit hub: Comelit Hub 1
...done: client agent id is 4
Sending message to HUB {"req_type":5,"seq_id":2,"req_sub_type":-1,"agent_type":0,"agent_id":4,"user_name":"admin","password":"admin"}
Message queue size is 1
Received message with id 2
Resolving promise 2: {
  req_type: 5,
  req_sub_type: -1,
  seq_id: 2,
  req_result: 0,
  uid: '65798145',
  sessiontoken: '21799799',
  status: NaN
}
Message processed. Message queue size is now 0
Sending message to HUB {"req_type":0,"seq_id":3,"req_sub_type":-1,"sessiontoken":"21799799","obj_id":"GEN#17#13#1","detail_level":1}
Message queue size is 1
Received message with id 3
Resolving promise 3: {
  req_type: 0,
  req_sub_type: -1,
  seq_id: 3,
  req_result: 0,
  out_data: [
    {
      id: 'GEN#17#13#1',
      type: 1001,
      sub_type: 13,
      descrizione: 'root',
      sched_status: '0',
      sched_lock: '1970-01-01 01:00:00',
      status: '0',
      powerst: '0',
      schedZoneStatus: [Array],
      elements: [Array]
    }
  ],
  count: 1,
  status: NaN
}
Message processed. Message queue size is now 0
Resolving response 3
Selected device does not exists
Shutting down
Comelit client unsubscribe from read topic
Comelit client ending session
Comelit client disconnected
Command others executed successfully
Exiting`

**Comment by madchicken** [comment]
Fixed in https://github.com/madchicken/comelit-client/commit/1710434e8d8912b91ab4f4b81c0248ed063ea231
