### ISSUE TITLE
Aiuto installazione

### ISSUE THREAD

**Issue by Vincenzopica** [madchicken/comelit-client#33]
Ciao, ho la necessità di installare questa finzione sul mio HA, vorrei sapere lo stato degli ingressi dell'antifurto vedo. Però non so da dove partire per installarlo puoi aiutarmi? Grazie

**Comment by joeyboey** [comment]
If I understand correctly you wann install this in Home Assistant?

The easiest way is to just use Node Red and install this module as a dependency.
If this is what you want let me know, I can write a quick tutorial :)

**Comment by Vincenzopica** [comment]
Ciao, si in Home Assistant

**Comment by joeyboey** [comment]
Check my community post from a few months ago :)
Setup is pretty simple and works reliably after that.

[https://community.home-assistant.io/t/comelit-video-intercom/15128/19?u=joeyboey](https://community.home-assistant.io/t/comelit-video-intercom/15128/19?u=joeyboey)

**Comment by Vincenzopica** [comment]
Grazie mille, spero di riuscirci, ho installato HA da poco devo ancora imparare... ma ci provo.

**Comment by joeyboey** [comment]
It's gonna be a little bit more complicated then. First step would be to install the NodeRED Addon. If you installed Home Assistant OS just use the plugin:

[NodeRED Addon](https://community.home-assistant.io/t/home-assistant-community-add-on-node-red/55023)

After that add the required package under the addon settings.
You should now be able to follow my quick writeup :)

**Comment by Vincenzopica** [comment]
niente mi sa troppo difficile, ho installato il componente ma oltre a quello non so proprio come fare

**Comment by Vincenzopica** [comment]
> Sarà un po' più complicato allora. Il primo passo sarebbe installare il componente aggiuntivo NodeRED. Se hai installato il sistema operativo Home Assistant, usa semplicemente il plug-in:
> 
> [Componente aggiuntivo NodeRED](https://community.home-assistant.io/t/home-assistant-community-add-on-node-red/55023)
> 
> Successivamente aggiungi il pacchetto richiesto nelle impostazioni del componente aggiuntivo. Ora dovresti essere in grado di seguire il mio rapido resoconto :)

ciao, sto cercando di lavorarci un po, non capisco pero come aggiungere il pacchetto al node-red
puoi fare una piccola guida ?

**Comment by madchicken** [comment]
@Vincenzopica credo che la cosa migliore sia chiedere aiuto alla community di Home Assistant, non su questo repository che non ha nulla a che fare con HA. Puoi magari tentare la strada sul loro canale Discord qui https://discord.com/invite/c5DvZ4e
