### ISSUE TITLE
blocca home assistant

### ISSUE THREAD

**Issue by Vincenzopica** [madchicken/comelit-client#47]
Ciao, se carico l'integrazione, inserisco i dati su configuration.yaml dopo il riavvio non carica più home assistant. lo raggiungo solo tramite samba, cancello da configuration la stringa di comelit e poi riparte.

**Comment by madchicken** [comment]
Scysa @Vincenzopica ma non sono assoluatamente pratico di home assustant e quindi non posso aiutarti
